### ISSUE TITLE
GENEPIO Ontology ID in json and xlsx does not match EBI Ontology Lookup Service

### ISSUE THREAD

**Issue by ErikaKvalem** [pha4ge/SARS-CoV-2-Contextual-Data-Specification#18]
As part of BU-ISCIII surveillance on SARS-CoV-2 genomic data we are currently working on mapping metadata terms among different database standards (ENA, GISAID and PHA4GE). We are learning from your _SARS-CoV-2-Contextual-Data-Specification file_ in xlsx and in Json. 

While doing so, we realized that when searching for GENEPIO terms in [EBI Ontology Lookup Service](https://www.ebi.ac.uk/ols/ontologies/genepio)   we cannot find the terms associated. 

An example of this would be when searching for  **"depth of coverage value"** in [EBI Ontology Lookup Service](https://www.ebi.ac.uk/ols/ontologies/genepio) The closest term is **read coverage** with **GENEPIO_0000092**.  However, in the Json and also in the xlsx  _SARS-CoV-2-Contextual-Data-Specification_  this term is linked to **GENEPIO:0001474**. 
![web](https://user-images.githubusercontent.com/39902241/150127142-566cc98d-ccb0-4943-a72b-53140dc3005d.png)

![excel_json](https://user-images.githubusercontent.com/39902241/150126957-a12634c4-3fcd-4994-a5f9-548ecd2d8dc1.png)
![json](https://user-images.githubusercontent.com/39902241/150127638-bf6a09d7-9ee5-4de4-baed-a29aa0669dd9.png)

Moreover, we found that when searching for **GENEPIO:0001474** in [EBI Ontology Lookup Service](https://www.ebi.ac.uk/ols/ontologies/genepio)  we cannot find any matching term. 
![1474](https://user-images.githubusercontent.com/39902241/150127918-69a61238-6438-4b4f-8704-9af97e258d79.png)

We have also searched in the GENEPIO reference file without success. [genepio.owl](https://github.com/GenEpiO/genepio/blob/master/genepio.owl) 

We wonder which are the correct GENEPIO  ontology ids associated with the terms.

**Comment by cimendes** [comment]
Thank you for bringing this issue to our attention. We are looking into it and will update you with information when available!
