### ISSUE TITLE
Proposal to add new fields

### ISSUE THREAD

**Issue by andersgs** [pha4ge/SARS-CoV-2-Contextual-Data-Specification#7]
We are discussing internally data changes to SARS-CoV-2 samples.

We are looking at adding:

1. Collected in Quarantine (boolean)
2. Vaccinated (boolean)
3. Vaccine (select among available)
4. Taken all doses?
5. Date of latest dose?

**Comment by cimendes** [comment]
closing as it was addressed in #8 (thanks @andersgs!)
