### ISSUE TITLE
Colour coding key missing from XLSX file

### ISSUE THREAD

**Issue by andersgs** [pha4ge/SARS-CoV-2-Contextual-Data-Specification#9]
I could not find a key for the colour code used in the XLSX file. Could we add a column to Reference Guide tab with values required, recommended, optional? That way the colouring would be obvious. Or perhaps it is already there, and I missed it.

I do see it in the README. :)

**Comment by cimendes** [comment]
Thanks for the suggestion! It's now in the latest version of the template. :)
